# Generated by Django 3.2.5 on 2021-09-14 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculum',
            options={'ordering': ['-id', 'name']},
        ),
        migrations.AlterModelTable(
            name='curriculum',
            table='firstapp_curriculum',
        ),
    ]
